version: "3.8"
services:
  alertmanager:
    image: quay.io/kubealex/eda-alertmanager
    ports: 
      - "9093:9093"
    hostname: alertmanager
    networks:
      - eda-ansible

  quarkus-client:
    image: quay.io/lordofthejars/eda-quarkus-tester:1.0.0
    hostname: eda-quarkus
    restart: on-failure
    ports: 
      - "8080:8080"
    networks:
      - eda-ansible

networks:
  eda-ansible:
    name: eda-ansible